name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup ssh
      run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/develop.key
            chmod 600 ~/.ssh/develop.key
            cat >>~/.ssh/config <<END
            Host develop
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/develop.key
              StrictHostKeyChecking no
            END
          env:
            SSH_USER: ${{ secrets.DEVELOP_SSH_USER }}
            SSH_KEY: ${{ secrets.DEVELOP_SSH_KEY }}
            SSH_HOST: ${{ secrets.DEVELOP_SSH_HOST }}                        
